positive_personality_traits = [
    "kindness",
    "empathy",
    "compassion",
    "generosity",
    "optimism",
    "courage",
    "gratitude",
    "humility",
    "resilience",
    "honesty",
    "integrity",
    "confidence",
    "creativity",
    "passion",
    "open-mindedness",
    "adaptability",
    "self-discipline",
    "forgiveness",
    "loyalty"
    ]
mundane_personality_traits = [
    "reserved",
    "practical",
    "introverted",
    "conventional",
    "logical",
    "observant",
    "organized",
    "detail-oriented",
    "cautious",
    "punctual",
    "reserved",
    "realistic",
    "rational",
    "independent",
    "structured",
    "steady",
    "analytical",
    "consistent",
    "methodical"
    ]
flawed_personality_traits = [
    "impulsive but passionate",
    "insecure but empathetic",
    "stubborn but determined",
    "arrogant but confident",
    "indecisive but open-minded",
    "pessimistic but realistic",
    "overly cautious but responsible",
    "overly trusting but optimistic",
    "impatient but driven",
    "overthinker but analytical",
    "perfectionist but detail-oriented",
    "overly competitive but ambitious",
    "procrastinator but creative",
    "overly self-critical but self-aware",
    "rebellious but independent",
    "insensitive but honest",
    "forgetful but forgiving",
    "moody but introspective",
    "sarcastic but witty",
    "shy but observant"
    ]
plant_hobbies = [
    "photosynthesis photography",
    "gardening",
    "botanical art",
    "leaf arranging",
    "watercolor painting of landscapes",
    "root exploration",
    "nature meditation",
    "listening to bird songs",
    "weather watching",
    "organizing a plant library",
    "bee and butterfly watching",
    "terrarium crafting",
    "plant propagation experiments",
    "reading about plant biology",
    "attending gardening workshops",
    "writing plant poetry",
    ]
talking_manners = [
    "formal and polite",
    "casual and friendly",
    "eloquent and articulate",
    "animated and enthusiastic",
    "soft-spoken and gentle",
    "authoritative and commanding",
    "stereotypical surfer dude style",
    "expressive and passionate",
    "witty and humorous",
    "sarcastic and ironic",
    "professional and business-like",
    "loud and boisterous",
    "thoughtful and contemplative",
    "precise and concise",
    "animated and energetic",
    "quirky and eccentric",
    "dramatic and theatrical",
    "stereotypical posh",
    "stereotypical hipster",
    "stereotypical southern style",
    "stereotypical valley girl",
    "punk",
    "preppy",
    "stereotypical nerdy",
    "stereotypical emo",
    "stereotypical country style",
    "classy"
    ]
