positive_personality_traits = [
    "Kindness",
    "Empathy",
    "Compassion",
    "Generosity",
    "Optimism",
    "Courage",
    "Gratitude",
    "Humility",
    "Resilience",
    "Honesty",
    "Integrity",
    "Confidence",
    "Creativity",
    "Passion",
    "Open-mindedness",
    "Adaptability",
    "Self-discipline",
    "Forgiveness",
    "Loyalty"
]
mundane_personality_traits = [
    "Reserved",
    "Practical",
    "Introverted",
    "Conventional",
    "Logical",
    "Observant",
    "Organized",
    "Detail-oriented",
    "Cautious",
    "Punctual",
    "Reserved",
    "Realistic",
    "Rational",
    "Independent",
    "Structured",
    "Steady",
    "Analytical",
    "Consistent",
    "Methodical"
]
flawed_personality_traits = [
    "Impulsive but passionate",
    "Insecure but empathetic",
    "Stubborn but determined",
    "Arrogant but confident",
    "Indecisive but open-minded",
    "Pessimistic but realistic",
    "Overly cautious but responsible",
    "Overly trusting but optimistic",
    "Impatient but driven",
    "Overthinker but analytical",
    "Perfectionist but detail-oriented",
    "Overly competitive but ambitious",
    "Procrastinator but creative",
    "Overly self-critical but self-aware",
    "Rebellious but independent",
    "Insensitive but honest",
    "Forgetful but forgiving",
    "Moody but introspective",
    "Sarcastic but witty",
    "Shy but observant"
]
plant_hobbies = [
    "Photosynthesis photography",
    "Gardening",
    "Botanical art",
    "Leaf arranging",
    "Watercolor painting of landscapes",
    "Root exploration",
    "Nature meditation",
    "Listening to bird songs",
    "Weather watching",
    "Organizing a plant library",
    "Bee and butterfly watching",
    "Terrarium crafting",
    "Plant propagation experiments",
    "Reading about plant biology",
    "Attending gardening workshops",
    "Writing plant poetry",
]
talking_manners = [
    "Formal and polite",
    "Casual and friendly",
    "Eloquent and articulate",
    "Animated and enthusiastic",
    "Soft-spoken and gentle",
    "Authoritative and commanding",
    "Laid-back and relaxed",
    "Expressive and passionate",
    "Witty and humorous",
    "Sarcastic and ironic",
    "Professional and business-like",
    "Loud and boisterous",
    "Thoughtful and contemplative",
    "Charming and charismatic",
    "Precise and concise",
    "Animated and energetic",
    "Calm and soothing",
    "Deliberate and measured",
    "Quirky and eccentric",
    "Dramatic and theatrical"
]
